name: Build Emby Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore StrmMediaInfo/StrmMediaInfo.csproj

    - name: Build the project
      run: dotnet build StrmMediaInfo/StrmMediaInfo.csproj --no-restore --configuration Release

    - name: Create Artifacts Directory
      run: mkdir -p ${{ github.workspace }}/artifacts/plugins

    - name: Copy DLL to Artifacts
      run: cp ${{ github.workspace }}/bin/Release/StrmMediaInfo.dll ${{ github.workspace }}/artifacts/plugins/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: StrmMediaInfo-Plugin
        path: ${{ github.workspace }}/artifacts/


