name: Build Evermedia Plugin

on:
  push:
    branches: [ main, v1 ]
  pull_request:
    branches: [ main, v1 ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # 修订：将工作目录指向 'Evermedia'
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./Evermedia

    # 修订：将工作目录指向 'Evermedia'
    - name: Build the project
      run: dotnet build --no-restore --configuration Release
      working-directory: ./Evermedia

    - name: Create Artifacts Directory
      run: mkdir -p ${{ github.workspace }}/artifacts/plugins

    # 修订：更新源路径和 .dll 文件名
    - name: Copy DLL to Artifacts
      run: cp ${{ github.workspace }}/Evermedia/bin/Release/Evermedia.dll ${{ github.workspace }}/artifacts/plugins/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        # 修订：更新构建产物的名称
        name: Evermedia-Plugin
        path: ${{ github.workspace }}/artifacts/


